version: '3'

services:
  db: 
    image: postgres:16.2
    restart: always
    ports : 
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: teslo-shop-db
    volumes:
      - ./postgres:/var/lib/postgresql/data